import { IMemory } from "@/shared-structures/IMemory";

const Memories: IMemory[] = [
  {
    title: "Twinkle my Cat & the trees bird’s & grass",
    description: "",
    first_name: "Susan",
    second_name: "Anne Williams. Likes to be called Sue.",
    email: "suewilliams337@gmail.com",
    recive: "",
    date: "2020-04-24T11:30:00.000Z",
    id: "kx6sp9me",
  },
  {
    title: "My Dad it would make me so happy",
    description: "I would be so happy",
    first_name: "Deborah",
    second_name: "Adams",
    email: "deb@jt-adams.co.uk",
    recive: "",
    date: "2020-08-05T04:15:00.000Z",
    id: "kx6sp72u",
  },
  {
    title: "My beautiful wife and family",
    description: "The personification of beauty, togetherness and love.",
    first_name: "Tony",
    second_name: "Chilton",
    email: "teecee01@sky.com",
    recive: "",
    date: "2020-12-16T19:37:00.000Z",
    id: "kx6sovaz",
  },
  {
    title: "So daughterand all grandkids",
    description: "",
    first_name: "Valerie",
    second_name: "Robson",
    email: "valerie_robson@sky.com",
    recive: "",
    date: "2021-01-01T19:57:00.000Z",
    id: "kx6sp6v4",
  },
  {
    title: "My daughter in her wedding dress",
    description:
      "I do have sight problems I cannot see in my left eye and need light!",
    first_name: "Annette",
    second_name: "Woosnam",
    email: "woosnamawoosnam@yahoo.com",
    recive: "",
    date: "2021-01-11T10:46:00.000Z",
    id: "kx6sp4jv",
  },
  {
    title: "My Beautiful Cat",
    description: "In among my Flowers in my Garden",
    first_name: "Gillian",
    second_name: "Blandford",
    email: "gill.11@hotmail.co.uk",
    recive: "",
    date: "2021-02-01T13:10:00.000Z",
    id: "kx6spa9g",
  },
  {
    title: "My Son and Husband",
    description: "",
    first_name: "Bridgett",
    second_name: "Gray",
    email: "b.gray265@btinternet.com",
    recive: "",
    date: "2021-02-17T13:01:00.000Z",
    id: "kx6soqi9",
  },
  {
    title: "my family",
    description: "I'd be so grateful 🙏",
    first_name: "Jan",
    second_name: "Lalande",
    email: "janlalande@hotmail.co.uk",
    recive: "",
    date: "2021-03-20T08:11:00.000Z",
    id: "kx6soygt",
  },
  {
    title: "The last time I saw my children",
    description:
      "It was when my daughters were together after one daughter returned for a visit from working abroad. Magical. We hadn't all been together for over a year.",
    first_name: "Mary",
    second_name: "Konig",
    email: "marykonig@gmail.com",
    recive: "",
    date: "2021-04-22T18:09:00.000Z",
    id: "kx6spjjo",
  },
  {
    title: "My two grandaughters' faces",
    description:
      "I'd see them happy & smiling with the backdrop of Loch lomond behind them.",
    first_name: "Madeline",
    second_name: "Cameron",
    email: "mandy1944@live.co.uk",
    recive: "",
    date: "2021-04-24T19:23:00.000Z",
    id: "kx6sot5j",
  },
  {
    title: "My grandchildren.",
    description: "I'd want to see my grandchildren.",
    first_name: "Joan",
    second_name: "Madeley",
    email: "joanmadeley5@gmail.com",
    recive: "",
    date: "2021-05-04T19:13:00.000Z",
    id: "kx6sp7ja",
  },
  {
    title: "My grandchildren",
    description: "",
    first_name: "Lorraine",
    second_name: "",
    email: "donnellyl46@yahoo.co.uk",
    recive: "",
    date: "2021-05-19T15:27:00.000Z",
    id: "kx6sp0vz",
  },
  {
    title: "The people I love.",
    description:
      "Well, they would have awesome new hairstyles & look extra special,  like angels 😇",
    first_name: "Sharon",
    second_name: "Letchford",
    email: "sharonletchford2020@gmail.com",
    recive: "",
    date: "2021-05-21T08:27:00.000Z",
    id: "kx6sp2gc",
  },
  {
    title: "The Monastery with all the Sangha",
    description: "Amazingly beautiful.",
    first_name: "Pema",
    second_name: "Drolkar",
    email: "majyoti@hotmail.co.uk",
    recive: "",
    date: "2021-06-12T15:12:00.000Z",
    id: "kx6soyyc",
  },
  {
    title: "My gorgeous wife",
    description: "",
    first_name: "Hubert",
    second_name: "Johnson",
    email: "eaglehj1@aol.com",
    recive: "",
    date: "2021-06-13T07:50:00.000Z",
    id: "kx6soose",
  },
  {
    title: "My family and dog.",
    description: "",
    first_name: "Margaret",
    second_name: "Frost",
    email: "margiefrost@hotmail.com",
    recive: "",
    date: "2021-07-10T08:48:00.000Z",
    id: "kx6sozwo",
  },
  {
    title: "My Husband and dogs",
    description: "Absolute heaven",
    first_name: "Kath",
    second_name: "Whitwam",
    email: "kathwhitwam@hotmail.com",
    recive: "",
    date: "2021-07-20T21:55:00.000Z",
    id: "kx6sp63c",
  },
  {
    title: "My whole family",
    description: "AT Christmas Dinner",
    first_name: "Helen",
    second_name: "Oakes",
    email: "cilygroes@hotmail.com",
    recive: "",
    date: "2021-07-28T14:06:00.000Z",
    id: "kx6spfsf",
  },
  {
    title: "my son",
    description: "",
    first_name: "Nabeil",
    second_name: "Amer",
    email: "anabeil@hotmail.com",
    recive: "",
    date: "2021-09-05T19:10:00.000Z",
    id: "kx6sp3oj",
  },
  {
    title: "family",
    description: "",
    first_name: "kim",
    second_name: "ireland",
    email: "kim.ireland68@hotmail.co.uk",
    recive: "",
    date: "2021-09-08T13:29:00.000Z",
    id: "kx6spiwe",
  },
  {
    title: "My children and grandchildren",
    description:
      "Sheer joy, clinging onto their laughter, their hugs, their respect for me, their passions, clinging onto the memories of their babyhood, their entire being!",
    first_name: "Jackie",
    second_name: "Martin",
    email: "antjaxinuk@btinternet.com",
    recive: "",
    date: "2021-09-14T15:16:00.000Z",
    id: "kx6soodm",
  },
  {
    title: "My children",
    description: "Beautiful, intensely emotional and incredible",
    first_name: "Nikki",
    second_name: "Matthews",
    email: "nicola_catchpole@hotmail.com",
    recive: "",
    date: "2021-09-25T14:18:00.000Z",
    id: "kx6soww6",
  },
  {
    title: "My mother",
    description:
      "I would love to picture my mother standing in front of me smiling but alas seeing or blind that will never happen again as she passed away a year ago",
    first_name: "Mary",
    second_name: "Nortcliff",
    email: "marytnortcliff@gmail.com",
    recive: "",
    date: "2021-09-26T13:39:00.000Z",
    id: "kx6spfho",
  },
  {
    title: "The Birth of my Son and my Daddy again!!",
    description: "",
    first_name: "Gemma",
    second_name: "Forrest",
    email: "gemma935@icloud.com",
    recive: "",
    date: "2021-09-27T07:56:00.000Z",
    id: "kx6sp0vc",
  },
  {
    title: "My family and friends",
    description: "",
    first_name: "Cheryl",
    second_name: "G",
    email: "chery.geary@googlemail.com",
    recive: "",
    date: "2021-09-27T11:32:00.000Z",
    id: "kx6sordx",
  },
  {
    title: "My family, wife, children & grandchildren",
    description: "Joyous",
    first_name: "George",
    second_name: "Woodhouse",
    email: "george.woodhouse2@gmail.com",
    recive: "",
    date: "2021-09-28T20:02:00.000Z",
    id: "kx6speup",
  },
  {
    title: "My kids running to the water in Norfolk",
    description:
      "Ollie and Jess were running along Holkam beach into the water and then back again, giggling and smiling. Neither had a swimming costume so both in their pants. Pure joy! ",
    first_name: "Jenny",
    second_name: "Kitchen",
    email: "jenny@yoyodesign.com",
    recive: "",
    date: "2021-09-30T13:04:00.000Z",
    id: "kx6sondc",
  },
  {
    title:
      "My family, in my favourite places growing up - the Isle of Wight & Australia.",
    description: "At that moment I'd feel safe, happy, fulfilled, and at home.",
    first_name: "Megan",
    second_name: "Deefholts",
    email: "megan.deefholts@yoyodesign.com",
    recive: "",
    date: "2021-09-30T13:20:00.000Z",
    id: "kx6spjav",
  },
  {
    title: "icebergs falling into the sea in Patagonia",
    description: "",
    first_name: "Lucy",
    second_name: "King",
    email: "lucykingplay@gmail.com",
    recive: "",
    date: "2021-09-30T13:30:00.000Z",
    id: "kx6soogx",
  },
  {
    title: "Family and friends",
    description: "",
    first_name: "Vanessa",
    second_name: "Kitchen",
    email: "vckitchen1949@gmail.com",
    recive: "",
    date: "2021-09-30T13:59:00.000Z",
    id: "kx6sp2n0",
  },
  {
    title: "The world through different eyes",
    description:
      "I found it so difficult to choose a single thing I'd want to see. I was sobbing at the thought of all the wonderful images and memories I'd miss if I lost my sight. It certainly made me more compassionate about the daily struggles and grief people with sight loss may have. So, after 3 years I'd see through a completely different set of eyes than before - appreciating every single image with a different level of depth.",
    first_name: "Samantha",
    second_name: "Payne",
    email: "sampayne24@gmail.com",
    recive: "",
    date: "2021-09-30T14:09:00.000Z",
    id: "kx6sopi4",
  },
  {
    title: "My little son's toothy smile",
    description: "Nothing gives me as much joy as seeing that beaming face.",
    first_name: "Sarah",
    second_name: "Junker",
    email: "sarah.junker1@gmail.com",
    recive: "",
    date: "2021-09-30T17:45:00.000Z",
    id: "kx6sp2fi",
  },
  {
    title: "My children's gorgeous smiley faces",
    description:
      "I can only imagine utter  heartbreak not being able to visibly see my children grow up and be able to know by the look on their faces how they were feeling. If I was able to see them again after three years I'm sure I would cry a lot of happy tears. It would be the most wondrous moment in the world.",
    first_name: "Kathryn",
    second_name: "Allen",
    email: "ksallen01@gmail.com",
    recive: "",
    date: "2021-10-01T08:00:00.000Z",
    id: "kx6sougv",
  },
  {
    title: "My children's faces",
    description: "",
    first_name: "Julia",
    second_name: "Beran",
    email: "julia@vintner.london",
    recive: "",
    date: "2021-10-01T13:19:00.000Z",
    id: "kx6sosrp",
  },
  {
    title: "My sons passing out parade at Sandhurst",
    description:
      "He has been set on an army career since quite young, so it would be a proud and emotional event.",
    first_name: "victoria",
    second_name: "Bailey",
    email: "vicibailey@icloud.com",
    recive: "",
    date: "2021-10-01T20:51:00.000Z",
    id: "kx6spic3",
  },
  {
    title: "The Ocean with a beautiful sunset",
    description:
      "To know that the day is coming to end end and tomorrow I may watch this vision again",
    first_name: "Beverley",
    second_name: "Fletcher",
    email: "bfassociatesltd@gmail.com",
    recive: "",
    date: "2021-10-01T22:08:00.000Z",
    id: "kx6spfv4",
  },
  {
    title: "My children giving me a hug",
    description: "Very special moment and emotional memories",
    first_name: "Mark",
    second_name: "Burgess",
    email: "markgw.burgess@gmail.com",
    recive: "",
    date: "2021-10-02T14:28:00.000Z",
    id: "kx6sonpo",
  },
  {
    title: "My grandsons Henry and Sebastian ❤️",
    description:
      "My heart opening up with love; and meeting my eyes with theirs. Hopefully a cuddle and a Hello Nanny! Then a babble of what they have been doing! And asking ‘where’s Grandad!’",
    first_name: "Linda",
    second_name: "Hill",
    email: "Lindahill82@gmail.com",
    recive: "",
    date: "2021-10-03T18:47:00.000Z",
    id: "kx6spmg5",
  },
  {
    title: "My family.",
    description:
      "Having a family barbecue, my son in law does a barbecue just fine.",
    first_name: "Jenny",
    second_name: "Oxborough",
    email: "oxocubes54@gmail.com",
    recive: "",
    date: "2021-10-04T03:49:00.000Z",
    id: "kx6spgf7",
  },
  {
    title: "My family",
    description:
      "I'd be on the beach, watching them in the waves, giving them a thumbs up when they catch a wave and loving this moment.",
    first_name: "Lizzie",
    second_name: "Bentley Bowers",
    email: "lizzie.bentleybowers@gmail.com",
    recive: "",
    date: "2021-10-04T06:07:00.000Z",
    id: "kx6spj4l",
  },
  {
    title: "Holding my my son and daughter!",
    description:
      "I would always feel happy and seek comfort in knowing that my son and daughter are in the world with me!",
    first_name: "Steve",
    second_name: "Goates",
    email: "stevegoates86@gmail.com",
    recive: "",
    date: "2021-10-04T07:36:00.000Z",
    id: "kx6spfej",
  },
  {
    title: "My grand children & great grandchildren",
    description: "Impossible to find the words",
    first_name: "Anne",
    second_name: "Houston",
    email: "ann3h0ust0n@gmail.com",
    recive: "",
    date: "2021-10-04T13:06:00.000Z",
    id: "kx6spk0e",
  },
  {
    title: "My son",
    description:
      "It would be like a dream a excellent dream 🙏🙏🙏🤩🤩🤩🤩✊✊✊❤️❤️❤️❤️❤️✊✊✊✊✊🤩🤩🤩🙏🙏🙏🙏🙏🙏🙏🙏🙏🙏🙏🙏🙏🙏",
    first_name: "Sharon Angela",
    second_name: "Grimshaw",
    email: "sharongrim@icloud.com",
    recive: "",
    date: "2021-10-04T23:19:00.000Z",
    id: "kx6somty",
  },
  {
    title: "My 3 children & 2 Grandsons",
    description:
      "It would be magical,my stomach would be turning with excitement at the thought of seeing all of their smiling faces .I would be excited at seeing how much my Grandsons had grown and changed in those 3 years,are they taller, have their faces changed, had logans hair darkened, Is Aiden taller then me now.Do my children look older now then I remember them looking .\n\n",
    first_name: "Angela",
    second_name: "Johnson",
    email: "angelaj7765@gmail.com",
    recive: "",
    date: "2021-10-05T16:56:00.000Z",
    id: "kx6spdqv",
  },
  {
    title: "My mum and dad",
    description: "Heart warming and safe",
    first_name: "Anisa",
    second_name: "V",
    email: "qwert@hotmail.com",
    recive: "",
    date: "2021-10-06T16:59:00.000Z",
    id: "kx6sorf1",
  },
  {
    title: "My phone",
    description: "That moment when I touch my phone",
    first_name: "Mandeep",
    second_name: "Douley",
    email: "mandeepdouley6@gmail.com",
    recive: "",
    date: "2021-10-07T09:37:00.000Z",
    id: "kx6soo3i",
  },
  {
    title: "Statue of jesus at rio de janerio",
    description: "Never seen",
    first_name: "Cath",
    second_name: "Kerr",
    email: "Scotcat13@gmail.com",
    recive: "",
    date: "2021-10-07T12:35:00.000Z",
    id: "kx6soksq",
  },
  {
    title: "My beautiful nephew ❣️",
    description: "",
    first_name: "Agnieszka",
    second_name: "Majewska",
    email: "amajewska25@gmail.com",
    recive: "",
    date: "2021-10-07T14:41:00.000Z",
    id: "kx6sp5rr",
  },
  {
    title: "My family in a group together",
    description:
      "\nTo see all of them united would bring a sense of joy all around",
    first_name: "Brian",
    second_name: "Jackson",
    email: "jacksonbrian53@yahoo.com",
    recive: "",
    date: "2021-10-08T10:17:00.000Z",
    id: "kx6sotwa",
  },
  {
    title: "The moment my daughter was born",
    description:
      "She was  beautiful and had so much black hair and fell hopelessly in love.",
    first_name: "Heidi",
    second_name: "Wilson",
    email: "doowhat1@sky.com",
    recive: "",
    date: "2021-10-08T15:31:00.000Z",
    id: "kx6soq8l",
  },
  {
    title: "My Husband and my Little Westie",
    description: "Fantastic",
    first_name: "Joan",
    second_name: "Doyle",
    email: "joandoyle35@yahoo.co.uk",
    recive: "",
    date: "2021-10-09T12:35:00.000Z",
    id: "kx6sp587",
  },
  {
    title: "My Loving wife",
    description:
      "who I have not kissed or held her hand in nearly 6 years.  The British Government's Immigration Policy ruined 2 lives.\n\nI don't have the money now and I'm old man of 75 years and my loving wife is 46 years old.  We need a miracle to get her into the UK...... she cries that she cannot care for me and I can't live in the Philippines due to the high cost of medical insurance.\nJust to hold her hand, touch her face.Antobio\n\n",
    first_name: "Tony",
    second_name: "Williams",
    email: "tony_williams.portsmouth@yahoo.co.uk",
    recive: "",
    date: "2021-10-10T19:54:00.000Z",
    id: "kx6somch",
  },
  {
    title: "Clare and our two boys",
    description: "Unconditional love, care and togetherness.",
    first_name: "Nick",
    second_name: "Fox",
    email: "foxpad@hotmail.com",
    recive: "",
    date: "2021-10-14T07:19:00.000Z",
    id: "kx6sos0v",
  },
  {
    title: "My daughters walking into school holding hands",
    description:
      "Letting your children go, when its their time to start school, is an emotional rollercoaster.  Pride, excitement, loneliness, sadness your time together, in their little years, is over.  This morning my girls - aged 7 and 4 - took each others hands and walked all the way from the gate, through the entrance, down the steps and to the reception classroom, without once letting go of each other's hands.  They smiled at each other, and chatted all the way.  It was magical and heart warming to watch.",
    first_name: "Anna",
    second_name: "Dixon",
    email: "annadixon@hotmail.co.uk",
    recive: "",
    date: "2021-10-14T07:36:00.000Z",
    id: "kx6spaht",
  },
  {
    title: "Me walking again, walking down the aisle to the man of my dreams",
    description:
      "I haven't been able to walk since 2008 when I suffered a stroke st the age of 30 becsuse of a brain haemmorrhage... my boyfriend has stuck with me through thick and thin... able bodied and disabled... he is a constant support fo me. I have accepted rhat my dad won't be able to give me away but to learn to walk Gain for my wedding day would mean the world to me. ",
    first_name: "Alex",
    second_name: "Wilmington",
    email: "awilmjngton1@gmail.com",
    recive: "",
    date: "2021-10-18T21:52:00.000Z",
    id: "kx6sp0ag",
  },
  {
    title: "My daughter’s smile",
    description: "",
    first_name: "Renata",
    second_name: "Benning",
    email: "renata.benning@gmail.com",
    recive: "",
    date: "2021-10-20T20:24:00.000Z",
    id: "kx6sp70i",
  },
  {
    title: "My children being born",
    description:
      "They were born and I thought I’d never feel the way I did again. Looking at their little faces was mind blowing",
    first_name: "Carol",
    second_name: "Collins",
    email: "carolcollins831@gmail.com",
    recive: "",
    date: "2021-10-20T20:53:00.000Z",
    id: "kx6soqvu",
  },
  {
    title: "My friends and my family",
    description:
      "It would be overwhelming, emotional and joyful all at the same time",
    first_name: "Bridget",
    second_name: "McClure-Jones",
    email: "bmcclurejones@gmail.com",
    recive: "",
    date: "2021-10-24T03:24:00.000Z",
    id: "kx6sot4d",
  },
  {
    title: "My daughter as a little girl again",
    description: "My daughter as a little girl again",
    first_name: "Maureen",
    second_name: "Boyd",
    email: "mo.boyd1939@gmail.com",
    recive: "",
    date: "2021-10-26T18:10:00.000Z",
    id: "kx6soqji",
  },
  {
    title: "The beach",
    description: "It’s my place of hope, love, great memories and freedom ",
    first_name: "David",
    second_name: "Bethell",
    email: "djbethell@gmail.com",
    recive: "",
    date: "2021-10-26T22:44:00.000Z",
    id: "kx6sp2ey",
  },
  {
    title: "My grandchildren",
    description: "",
    first_name: "weaver",
    second_name: "Sharon",
    email: "sharon654_89@hotmail.com",
    recive: "",
    date: "2021-10-27T10:39:00.000Z",
    id: "kx6son4l",
  },
  {
    title: "Robbie Williams  singing",
    description:
      "at a distance that I could see him my sight is getting less each day and I'm registers blind already",
    first_name: "Sheila",
    second_name: "Smedley",
    email: "sheilasmedley202@gmail.com",
    recive: "",
    date: "2021-10-27T15:25:00.000Z",
    id: "kx6sphdf",
  },
  {
    title: "Then faces of my children",
    description: "Overwhelming joy\n",
    first_name: "Ronalda",
    second_name: "Larsen",
    email: "ronaldalarsen@outlook.com",
    recive: "",
    date: "2021-10-31T18:17:00.000Z",
    id: "kx6soy2v",
  },
  {
    title: "My family happy & all together",
    description: "Pure Joy & Gratitude ❤️❤️",
    first_name: "Anita",
    second_name: "Foster",
    email: "anitamfoster@mail.com",
    recive: "",
    date: "2021-11-02T16:57:00.000Z",
    id: "kx6solax",
  },
  {
    title: "the beach",
    description: "",
    first_name: "Cecilia",
    second_name: "Canizela",
    email: "ceciliacanizela@hotmail.com",
    recive: "",
    date: "2021-11-04T01:17:00.000Z",
    id: "kx6spf1y",
  },
  {
    title: "My partner and stepson smiling at me",
    description:
      "It would be at a happy holiday destination we love, and would be a moment of pure joy",
    first_name: "Suzy",
    second_name: "Bradley",
    email: "suzi.turnee@icloud.com",
    recive: "",
    date: "2021-11-04T11:00:00.000Z",
    id: "kx6spcxz",
  },
  {
    title: "All my blind frieñds get their sight back",
    description: "Elation and gratitude because they deserve it!",
    first_name: "Stephen",
    second_name: "McGoldrick",
    email: "steve.mcg0512@gmail.com",
    recive: "",
    date: "2021-11-04T13:38:00.000Z",
    id: "kx6spasr",
  },
  {
    title: "my family",
    description: "",
    first_name: "elizabeth",
    second_name: "Russell",
    email: "elizabethrussell297@btinternet.com",
    recive: "",
    date: "2021-11-06T08:33:00.000Z",
    id: "kx6sp45s",
  },
  {
    title: "My sons and my husband and sisters",
    description: "",
    first_name: "Mrs Julienne",
    second_name: "Fantom",
    email: "juliennefantom@icloud.com",
    recive: "",
    date: "2021-11-10T00:15:00.000Z",
    id: "kx6spb6i",
  },
  {
    title: "Family faces",
    description:
      "Yes if the vision blurred can’t see the feature properly but know them when they talk recognise there voice",
    first_name: "Hana",
    second_name: "Jarr",
    email: "greenoaktree241@yahoo.com",
    recive: "",
    date: "2021-11-10T14:18:00.000Z",
    id: "kx6sonq6",
  },
  {
    title: "My children",
    description: "Love",
    first_name: "Robert",
    second_name: "Robert Hirst mi",
    email: "bobhirst383@gmail.com",
    recive: "",
    date: "2021-11-12T01:20:00.000Z",
    id: "kx6soon0",
  },
  {
    title: "I would see my newborn baby",
    description: "Magical Love Like no other",
    first_name: "Stephanie",
    second_name: "hood",
    email: "stephaniehood1@outlook.com",
    recive: "",
    date: "2021-11-12T17:45:00.000Z",
    id: "kx6sorkx",
  },
  {
    title: "My new granddaughter",
    description:
      "My daughter wanted to share their home with one more child - they had two boys of their own. When we saw our new little granddaughter for the first time it was a vey spccial moment that I would hope never to have missed. The reaction on her brother's faces, their pride in having a sister. She looked so different to them, but she was amazing - such a precious moment to see. How hard not to be able to do so. \n",
    first_name: "Helen",
    second_name: "Burridge",
    email: "hlandajburridge@yahoo.co.uk",
    recive: "",
    date: "2021-11-12T18:10:00.000Z",
    id: "kx6spa4f",
  },
  {
    title: "The glorious view of the autumn colors and the shimmering lake",
    description:
      "The trees are resplendent with vibrant reds, golden yellow, orange , amber leaves fluttering in the wind. The ground is littered with red orangey leaves like a lush carpet underfoot. The lake's reflection of the trees above seems alive with a riot of colors. Everywhere there is the vibrant color of the trees and plants, something which will always stay in my mind forever!",
    first_name: "Jan",
    second_name: "Cae",
    email: "wonderfulnow@gmail.com",
    recive: "",
    date: "2021-11-13T07:44:00.000Z",
    id: "kx6sp3gb",
  },
  {
    title: "My great grandchildren",
    description: "Tearful recognition",
    first_name: "Pam",
    second_name: "Mitchell",
    email: "pam-mitchell@outlook.com",
    recive: "",
    date: "2021-11-13T21:16:00.000Z",
    id: "kx6soyah",
  },
  {
    title: "La Coruña",
    description:
      "A restaraunt date with my ex girlfriend with the sunset. Best moment of my life",
    first_name: "Caspian",
    second_name: "North",
    email: "junkmailman245@gmail.com",
    recive: "",
    date: "2021-11-13T22:20:00.000Z",
    id: "kx6spczm",
  },
  {
    title: "A Hoylake sunset after clouds clear",
    description:
      "All the colours…blue sky, grey clouds with golden sun setting over the Welsh Hills reflecting on the wet sand.  Turning different shades of pink when the sun disappears.",
    first_name: "Christine",
    second_name: "Jones",
    email: "chris24658@yahoo.co.uk",
    recive: "",
    date: "2021-11-14T05:22:00.000Z",
    id: "kx6spfds",
  },
  {
    title:
      "My family my grandchildren and great grandkids and my church family",
    description: "",
    first_name: "Patricia",
    second_name: "Simpson",
    email: "patriciasimpson265@gmail.com",
    recive: "",
    date: "2021-11-14T14:21:00.000Z",
    id: "kx6sp7vu",
  },
  {
    title: "My dear husband with grown up children with their children!",
    description: "The mo ment would be full of love ,joy and laughter!",
    first_name: "Dorothy",
    second_name: "Needham",
    email: "needhamdf@yahoo.com",
    recive: "",
    date: "2021-11-15T17:01:00.000Z",
    id: "kx6soqd0",
  },
  {
    title: "I'd like to see my Dog",
    description: "I've not experienced that moment yer because I'm not blind",
    first_name: "Jean",
    second_name: "Merron",
    email: "jeanmerron42@talktalk.net",
    recive: "",
    date: "2021-11-18T04:54:00.000Z",
    id: "kx6sph32",
  },
  {
    title:
      "My darling Dad who fought in Burma behind the Japanese lines!  He was a wonderful gardener who won hundreds of prizes at Denbigh flower shows.",
    description:
      "I would hug and kiss him and tell him how much I loved him xxx",
    first_name: "Jacky",
    second_name: "Bond",
    email: "jacky01908@gmail.com",
    recive: "",
    date: "2021-11-19T15:02:00.000Z",
    id: "kx6sp75s",
  },
  {
    title: "Green Hills and blue skies",
    description: "The countryside away from hustle and bustle of busy life.",
    first_name: "John",
    second_name: "Dicker",
    email: "johndicker12@gmail.com",
    recive: "",
    date: "2021-11-20T18:32:00.000Z",
    id: "kx6sp3vp",
  },
  {
    title: "All my family would just love to see them all together",
    description: "Amazing",
    first_name: "Valerie",
    second_name: "Mutton",
    email: "vnickson.mutton@gmail.com",
    recive: "",
    date: "2021-11-21T07:16:00.000Z",
    id: "kx6soqvr",
  },
  {
    title: "My four grandchildren.",
    description:
      "It's always so lovely to see them. They are all very loving and it's such a joy to get hugs from them.",
    first_name: "Joy",
    second_name: "Osborn",
    email: "ossjoy@hotmail.co.uk",
    recive: "",
    date: "2021-11-24T15:51:00.000Z",
    id: "kx6somqd",
  },
  {
    title: "My children",
    description: "Wonderful Amazing i love my kids",
    first_name: "Kevin",
    second_name: "Johnston",
    email: "kevj14081970@gmail.com",
    recive: "",
    date: "2021-11-28T21:09:00.000Z",
    id: "kx6sotpa",
  },
  {
    title: "My mum and brother",
    description: "",
    first_name: "Phillup",
    second_name: "Jones",
    email: "papajones@talktalk.net",
    recive: "",
    date: "2021-12-01T07:08:00.000Z",
    id: "kx6sp4tz",
  },
  {
    title:
      "I would really LOVE to see the village of Stonyford, in county Kilkenny, Southern Ireland.",
    description: "Pure Tranquility",
    first_name: "Ken",
    second_name: "Fennelly",
    email: "nelly2fenn@gmail.com",
    recive: "",
    date: "2021-12-05T19:30:00.000Z",
    id: "kx6spm3s",
  },
  {
    title: "My grandchildren faces",
    description: "Excitement, joy",
    first_name: "Johnstone",
    second_name: "Edwina",
    email: "edpatruth@gmail.com",
    recive: "",
    date: "2018-11-26T09:44:00.000Z",
    id: "kx6spbyd",
  },
  {
    title: "a mountain range",
    description: "",
    first_name: "Andrew",
    second_name: "Johnson",
    email: "a.l.a.johnson@outlook.com",
    recive: "",
    date: "2018-11-26T09:44:00.000Z",
    id: "kx6sp45w",
  },
  {
    title:
      "I'd see both my grand daughters💓   I  love you both my grand daughters",
    description: "Seeing them is better than  taking Prozac",
    first_name: "Sylvia",
    second_name: "Jenkins",
    email: "sylviamashy48@gmail.com",
    recive: "",
    date: "2018-11-26T09:44:00.000Z",
    id: "kx6spkj8",
  },
  {
    title: "My husband's face",
    description: "",
    first_name: "Jane",
    second_name: "Mountford",
    email: "jane.mountford@gmail.com",
    recive: "",
    date: "2019-06-14T12:47:00.000Z",
    id: "kx6son5l",
  },
  {
    title: "My nephew's smile",
    description: "",
    first_name: "Tony",
    second_name: "Ngaithe",
    email: "tngaithe@orbis.org.uk",
    recive: "",
    date: "2019-10-10T14:39:00.000Z",
    id: "kx6sp96m",
  },
  {
    title: "My beloved cat Smokey",
    description: "Smokey jumping up into my lap purring",
    first_name: "Sam",
    second_name: "Harris",
    email: "sharris@orbis.org.uk",
    recive: "n",
    date: "2021-12-13T21:00:00.000Z",
    id: "kx6soovu",
  },
];

export { Memories as default };
